import localFont from "next/font/local";
import "./globals.css";
import { Inter, Outfit } from "next/font/google";
import Header from "@/components/Header";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const outfit = Outfit({
  subsets: ["latin"],
  variable: "--font-outfit", // Defining a CSS variable
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${outfit.variable} ${geistMono.variable} antialiased`}
      >
      {/* <div className="px-4 hero w-full md:px-12">
      <Header/> */}
      {children}
      {/* </div> */}
        
      </body>
    </html>
  );
}
